[package]
name = "cjval"
version = "0.2.0"
description = "CityJSON validator"
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/cityjson/cjval"
repository = "https://github.com/cityjson/cjval"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonschema = { version = "0.12.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.10.0"
structopt = "0.3.23"
url = "2.2.2"
ansi_term = "0.12"
# indexmap = "1.7.0"
# reqwest = "0.11.5"
# tokio = { version = "1", features = ["full"] }

[dependencies.clap]
version = "2"
default-features = false
features = ["suggestions", "color", "wrap_help"]